## Glassdoor Jobs Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings ('ignore')

#### Load Data

In [2]:
# Load data
df = pd.read_csv('v1.2.csv')

In [3]:
df.head()

,Unnamed: 0,Unnamed: 1,GLASSDOOR JOBS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Competitors,Revenue,Sector,Industry,Ownership Type,Founded,Size,Headquarters,Location,Name,Rating,Description,Salary,Title,index
3,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist,0
4,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist,1

In [4]:
df = pd.read_csv ('v1.2.csv', skiprows= 3)
df.head()

,Competitors,Revenue,Sector,Industry,Ownership Type,Founded,Size,Headquarters,Location,Name,Rating,Description,Salary,Title,index
0,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist,0
1,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist,1
2,-1,$100 to $500 million (USD),Business Services,Consulting,Private Practice / Firm,1981,1001 to 5000 employees,"Boston, MA","Boston, MA",Analysis Group\n3.8,3.8,Overview\n\n\nAnalysis Group is one of the lar...,$137K-$171K (Glassdoor est.),Data Scientist,2
3,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",$100 to $500 million (USD),Manufacturing,Electrical & Electronic Manufacturing,Company - Public,2000,501 to 1000 employees,"Bad Ragaz, Switzerland","Newton, MA",INFICON\n3.5,3.5,JOB DESCRIPTION:\n\nDo you have a passion for ...,$137K-$171K (Glassdoor est.),Data Scientist,3
4,"Commerce Signals, Cardlytics, Yodlee",Unknown / Non-Applicable,Business Services,Advertising & Marketing,Company - Private,1998,51 to 200 employees,"New York, NY","New York, NY",Affinity Solutions\n2.9,2.9,Data Scientist\nAffinity Solutions / Marketing...,$137K-$171K (Glassdoor est.),NaN,4

In [5]:
df.drop ('index', axis=1, inplace=True)

In [6]:
df.head()

,Competitors,Revenue,Sector,Industry,Ownership Type,Founded,Size,Headquarters,Location,Name,Rating,Description,Salary,Title
0,"EmblemHealth, UnitedHealth Group, Aetna",Unknown / Non-Applicable,Insurance,Insurance Carriers,Nonprofit Organization,1993,1001 to 5000 employees,"New York, NY","New York, NY",Healthfirst\n3.1,3.1,Description\n\nThe Senior Data Scientist is re...,$137K-$171K (Glassdoor est.),Sr Data Scientist
1,-1,$1 to $2 billion (USD),Business Services,Research & Development,Company - Public,1968,5001 to 10000 employees,"Herndon, VA","Chantilly, VA",ManTech\n4.2,4.2,"Secure our Nation, Ignite your Future\n\nJoin ...",$137K-$171K (Glassdoor est.),Data Scientist
2,-1,$100 to $500 million (USD),Business Services,Consulting,Private Practice / Firm,1981,1001 to 5000 employees,"Boston, MA","Boston, MA",Analysis Group\n3.8,3.8,Overview\n\n\nAnalysis Group is one of the lar...,$137K-$171K (Glassdoor est.),Data Scientist
3,"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",$100 to $500 million (USD),Manufacturing,Electrical & Electronic Manufacturing,Company - Public,2000,501 to 1000 employees,"Bad Ragaz, Switzerland","Newton, MA",INFICON\n3.5,3.5,JOB DESCRIPTION:\n\nDo you have a passion for ...,$137K-$171K (Glassdoor est.),Data Scientist
4,"Commerce Signals, Cardlytics, Yodlee",Unknown / Non-Applicable,Business Services,Advertising & Marketing,Company - Private,1998,51 to 200 employees,"New York, NY","New York, NY",Affinity Solutions\n2.9,2.9,Data Scientist\nAffinity Solutions / Marketing...,$137K-$171K (Glassdoor est.),NaN